# Generated by Django 5.0.4 on 2024-06-25 11:58

from django.db import migrations


def assign_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons_to_update = []

    for person in person_model.objects.all():
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'
        persons_to_update.append(person)

    person_model.objects.bulk_update(persons_to_update, ['age_group'])


def reverse_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons_to_update = []

    # for person in person_model.objects.all():
    #     person.age_group = person_model._meta.get_field('age_group').default
    #     persons_to_update.append(person)

    age_group_default = person_model._meta.get_field('age_group').get_default()

    if callable(age_group_default):
        age_group_default = age_group_default()  # Checks and Calls if it's callable

    for person in person_model.objects.all():    # Possibly better way than just .default
        person.age_group = age_group_default
        persons_to_update.append(person)

    person_model.objects.bulk_update(persons_to_update, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(assign_age_group, reverse_age_group)
    ]
